# By Harsh H. Rajpurohit
name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: "none"

# App Version
version: 1.0.2+2

environment:
  sdk: ">=3.4.3 <4.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter

  # Getx for state management
  get: ^4.6.6

  # Cupertino style icons
  cupertino_icons: ^1.0.8

  # For API Call
  http: ^1.2.1

  # Converting CSV data to List
  csv: ^6.0.0

  # For Lottie Animation
  lottie: ^3.1.2

  # For storing data (in local storage)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # For integrating ads
  google_mobile_ads: ^5.1.0

  # For firebase
  firebase_core: ^3.2.0

  # For Remote Config
  firebase_remote_config: ^5.0.3

  # Others
  countries_world_map: ^1.3.0
  flutter_onboarding_slider: ^1.0.11
  shared_preferences: ^2.2.3
  after_layout: ^1.2.0
  google_fonts: ^6.2.1
  onesignal_flutter: ^5.2.2

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  flutter_test:
    sdk: flutter

  # Change package name
  # change_app_package_name: ^1.1.0

  # Encourages good practices
  flutter_lints: ^4.0.0

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/lottie/
    - assets/flags/
