 import 'package:countries_world_map/data/maps/world_map.dart';
import 'package:countries_world_map/countries_world_map.dart';

import 'package:flutter/material.dart';
import 'package:vpn_basic_project/main.dart';

class CountryMap extends StatelessWidget {
   final String selectedCountry; 
    CountryMap({super.key, required this.selectedCountry,});


  

  @override
  Widget build(BuildContext context) {
    Color conditionColor=Theme.of(context).brightness == Brightness.dark
                            ?Colors.white
                            : Color(0xff0132cc);
    return Padding(
      padding:  EdgeInsets.symmetric(horizontal: mq.width * .03),
      child: SimpleMap(
        // String of instructions to draw the map.
        instructions: SMapWorld.instructions,
      
        // Default color for all countries.
        defaultColor: Color(0xff0132cc),
      
        // Matching class to specify custom colors for each area.
        colors: SMapWorldColors(
          aF: selectedCountry == 'Afghanistan' ? conditionColor: Color(0xff819ffe),
          aL: selectedCountry == 'Albania' ? conditionColor: Color(0xff819ffe),
          dZ: selectedCountry == 'Algeria' ? conditionColor: Color(0xff819ffe),
          aS: selectedCountry == 'American Samoa' ? conditionColor: Color(0xff819ffe),
          aD: selectedCountry == 'Andorra' ? conditionColor: Color(0xff819ffe),
          aO: selectedCountry == 'Angola' ? conditionColor: Color(0xff819ffe),
          aI: selectedCountry == 'Anguilla' ? conditionColor: Color(0xff819ffe),
          aQ: selectedCountry == 'Antarctica' ? conditionColor: Color(0xff819ffe),
          aG: selectedCountry == 'Antigua and Barbuda' ? conditionColor: Color(0xff819ffe),
          aR: selectedCountry == 'Argentina' ? conditionColor: Color(0xff819ffe),
          aM: selectedCountry == 'Armenia' ? conditionColor: Color(0xff819ffe),
          aW: selectedCountry == 'Aruba' ? conditionColor: Color(0xff819ffe),
          aU: selectedCountry == 'Australia' ? conditionColor: Color(0xff819ffe),
          aT: selectedCountry == 'Austria' ? conditionColor: Color(0xff819ffe),
          aZ: selectedCountry == 'Azerbaijan' ? conditionColor: Color(0xff819ffe),
          bS: selectedCountry == 'Bahamas (the)' ? conditionColor: Color(0xff819ffe),
          bH: selectedCountry == 'Bahrain' ? conditionColor: Color(0xff819ffe),
          bD: selectedCountry == 'Bangladesh' ? conditionColor: Color(0xff819ffe),
          bB: selectedCountry == 'Barbados' ? conditionColor: Color(0xff819ffe),
          bY: selectedCountry == 'Belarus' ? conditionColor: Color(0xff819ffe),
          bE: selectedCountry == 'Belgium' ? conditionColor: Color(0xff819ffe),
          bZ: selectedCountry == 'Belize' ? conditionColor: Color(0xff819ffe),
          bJ: selectedCountry == 'Benin' ? conditionColor: Color(0xff819ffe),
          bM: selectedCountry == 'Bermuda' ? conditionColor: Color(0xff819ffe),
          bT: selectedCountry == 'Bhutan' ? conditionColor: Color(0xff819ffe),
          bO: selectedCountry == 'Bolivia (Plurinational State of)' ? conditionColor: Color(0xff819ffe),
          bQ: selectedCountry == 'Bonaire, Sint Eustatius and Saba' ? conditionColor: Color(0xff819ffe),
          bA: selectedCountry == 'Bosnia and Herzegovina' ? conditionColor: Color(0xff819ffe),
          bW: selectedCountry == 'Botswana' ? conditionColor: Color(0xff819ffe),
          bV: selectedCountry == 'Bouvet Island' ? conditionColor: Color(0xff819ffe),
          bR: selectedCountry == 'Brazil' ? conditionColor: Color(0xff819ffe),
          iO: selectedCountry == 'British Indian Ocean Territory (the)' ? conditionColor: Color(0xff819ffe),
          bN: selectedCountry == 'Brunei Darussalam' ? conditionColor: Color(0xff819ffe),
          bG: selectedCountry == 'Bulgaria' ? conditionColor: Color(0xff819ffe),
          bF: selectedCountry == 'Burkina Faso' ? conditionColor: Color(0xff819ffe),
          bI: selectedCountry == 'Burundi' ? conditionColor: Color(0xff819ffe),
          cV: selectedCountry == 'Cabo Verde' ? conditionColor: Color(0xff819ffe),
          kH: selectedCountry == 'Cambodia' ? conditionColor: Color(0xff819ffe),
          cM: selectedCountry == 'Cameroon' ? conditionColor: Color(0xff819ffe),
          cA: selectedCountry == 'Canada' ? conditionColor: Color(0xff819ffe),
          kY: selectedCountry == 'Cayman Islands (the)' ? conditionColor: Color(0xff819ffe),
          cF: selectedCountry == 'Central African Republic (the)' ? conditionColor: Color(0xff819ffe),
          tD: selectedCountry == 'Chad' ? conditionColor: Color(0xff819ffe),
          cL: selectedCountry == 'Chile' ? conditionColor: Color(0xff819ffe),
          cN: selectedCountry == 'China' ? conditionColor: Color(0xff819ffe),
          cX: selectedCountry == 'Christmas Island' ? conditionColor: Color(0xff819ffe),
          cC: selectedCountry == 'Cocos (Keeling) Islands (the)' ? conditionColor: Color(0xff819ffe),
          cO: selectedCountry == 'Colombia' ? conditionColor: Color(0xff819ffe),
          kM: selectedCountry == 'Comoros (the)' ? conditionColor: Color(0xff819ffe),
          cD: selectedCountry == 'Congo (the Democratic Republic of the)' ? conditionColor: Color(0xff819ffe),
          cG: selectedCountry == 'Congo (the)' ? conditionColor: Color(0xff819ffe),
          cK: selectedCountry == 'Cook Islands (the)' ? conditionColor: Color(0xff819ffe),
          cR: selectedCountry == 'Costa Rica' ? conditionColor: Color(0xff819ffe),
          hR: selectedCountry == 'Croatia' ? conditionColor: Color(0xff819ffe),
          cU: selectedCountry == 'Cuba' ? conditionColor: Color(0xff819ffe),
          cW: selectedCountry == 'Curaçao' ? conditionColor: Color(0xff819ffe),
          cY: selectedCountry == 'Cyprus' ? conditionColor: Color(0xff819ffe),
          cZ: selectedCountry == 'Czechia' ? conditionColor: Color(0xff819ffe),
          cI: selectedCountry == 'Côte d\'Ivoire' ? conditionColor: Color(0xff819ffe),
          dK: selectedCountry == 'Denmark' ? conditionColor: Color(0xff819ffe),
          dJ: selectedCountry == 'Djibouti' ? conditionColor: Color(0xff819ffe),
          dM: selectedCountry == 'Dominica' ? conditionColor: Color(0xff819ffe),
          dO: selectedCountry == 'Dominican Republic (the)' ? conditionColor: Color(0xff819ffe),
          eC: selectedCountry == 'Ecuador' ? conditionColor: Color(0xff819ffe),
          eG: selectedCountry == 'Egypt' ? conditionColor: Color(0xff819ffe),
          sV: selectedCountry == 'El Salvador' ? conditionColor: Color(0xff819ffe),
          gQ: selectedCountry == 'Equatorial Guinea' ? conditionColor: Color(0xff819ffe),
          eR: selectedCountry == 'Eritrea' ? conditionColor: Color(0xff819ffe),
          eE: selectedCountry == 'Estonia' ? conditionColor: Color(0xff819ffe),
          sZ: selectedCountry == 'Eswatini' ? conditionColor: Color(0xff819ffe),
          eT: selectedCountry == 'Ethiopia' ? conditionColor: Color(0xff819ffe),
          fK: selectedCountry == 'Falkland Islands (the) [Malvinas]' ? conditionColor: Color(0xff819ffe),
          fO: selectedCountry == 'Faroe Islands (the)' ? conditionColor: Color(0xff819ffe),
          fJ: selectedCountry == 'Fiji' ? conditionColor: Color(0xff819ffe),
          fI: selectedCountry == 'Finland' ? conditionColor: Color(0xff819ffe),
          fR: selectedCountry == 'France' ? conditionColor: Color(0xff819ffe),
          gF: selectedCountry == 'French Guiana' ? conditionColor: Color(0xff819ffe),
          pF: selectedCountry == 'French Polynesia' ? conditionColor: Color(0xff819ffe),
          tF: selectedCountry == 'French Southern Territories (the)' ? conditionColor: Color(0xff819ffe),
          gA: selectedCountry == 'Gabon' ? conditionColor: Color(0xff819ffe),
          gM: selectedCountry == 'Gambia (the)' ? conditionColor: Color(0xff819ffe),
          gE: selectedCountry == 'Georgia' ? conditionColor: Color(0xff819ffe),
          dE: selectedCountry == 'Germany' ? conditionColor: Color(0xff819ffe),
          gH: selectedCountry == 'Ghana' ? conditionColor: Color(0xff819ffe),
          gI: selectedCountry == 'Gibraltar' ? conditionColor: Color(0xff819ffe),
          gR: selectedCountry == 'Greece' ? conditionColor: Color(0xff819ffe),
          gL: selectedCountry == 'Greenland' ? conditionColor: Color(0xff819ffe),
          gD: selectedCountry == 'Grenada' ? conditionColor: Color(0xff819ffe),
          gP: selectedCountry == 'Guadeloupe' ? conditionColor: Color(0xff819ffe),
          gU: selectedCountry == 'Guam' ? conditionColor: Color(0xff819ffe),
          gT: selectedCountry == 'Guatemala' ? conditionColor: Color(0xff819ffe),
          gG: selectedCountry == 'Guernsey' ? conditionColor: Color(0xff819ffe),
          gN: selectedCountry == 'Guinea' ? conditionColor: Color(0xff819ffe),
          gW: selectedCountry == 'Guinea-Bissau' ? conditionColor: Color(0xff819ffe),
          gY: selectedCountry == 'Guyana' ? conditionColor: Color(0xff819ffe),
          hT: selectedCountry == 'Haiti' ? conditionColor: Color(0xff819ffe),
          hM: selectedCountry == 'Heard Island and McDonald Islands' ? conditionColor: Color(0xff819ffe),
          vA: selectedCountry == 'Holy See (the)' ? conditionColor: Color(0xff819ffe),
          hN: selectedCountry == 'Honduras' ? conditionColor: Color(0xff819ffe),
          hK: selectedCountry == 'Hong Kong' ? conditionColor: Color(0xff819ffe),
          hU: selectedCountry == 'Hungary' ? conditionColor: Color(0xff819ffe),
          iS: selectedCountry == 'Iceland' ? conditionColor: Color(0xff819ffe),
          iN: selectedCountry == 'India' ? conditionColor: Color(0xff819ffe),
          iD: selectedCountry == 'Indonesia' ? conditionColor: Color(0xff819ffe),
          iR: selectedCountry == 'Iran (Islamic Republic of)' ? conditionColor: Color(0xff819ffe),
          iQ: selectedCountry == 'Iraq' ? conditionColor: Color(0xff819ffe),
          iE: selectedCountry == 'Ireland' ? conditionColor: Color(0xff819ffe),
          iM: selectedCountry == 'Isle of Man' ? conditionColor: Color(0xff819ffe),
          iL: selectedCountry == 'Israel' ? conditionColor: Color(0xff819ffe),
          iT: selectedCountry == 'Italy' ? conditionColor: Color(0xff819ffe),
          jM: selectedCountry == 'Jamaica' ? conditionColor: Color(0xff819ffe),
          jP: selectedCountry == 'Japan' ? conditionColor: Color(0xff819ffe),
          jE: selectedCountry == 'Jersey' ? conditionColor: Color(0xff819ffe),
          jO: selectedCountry == 'Jordan' ? conditionColor: Color(0xff819ffe),
          kZ: selectedCountry == 'Kazakhstan' ? conditionColor: Color(0xff819ffe),
          kE: selectedCountry == 'Kenya' ? conditionColor: Color(0xff819ffe),
          kI: selectedCountry == 'Kiribati' ? conditionColor: Color(0xff819ffe),
          kP: selectedCountry == 'Korea (the Democratic People\'s Republic of)' ? conditionColor: Color(0xff819ffe),
          kR: selectedCountry == 'Korea (the Republic of)' ? conditionColor: Color(0xff819ffe),
          xK: selectedCountry == 'Kosovo' ? conditionColor: Color(0xff819ffe),
          kW: selectedCountry == 'Kuwait' ? conditionColor: Color(0xff819ffe),
          kG: selectedCountry == 'Kyrgyzstan' ? conditionColor: Color(0xff819ffe),
          lA: selectedCountry == 'Lao People\'s Democratic Republic (the)' ? conditionColor: Color(0xff819ffe),
          lV: selectedCountry == 'Latvia' ? conditionColor: Color(0xff819ffe),
          lB: selectedCountry == 'Lebanon' ? conditionColor: Color(0xff819ffe),
          lS: selectedCountry == 'Lesotho' ? conditionColor: Color(0xff819ffe),
          lR: selectedCountry == 'Liberia' ? conditionColor: Color(0xff819ffe),
          lY: selectedCountry == 'Libya' ? conditionColor: Color(0xff819ffe),
          lI: selectedCountry == 'Liechtenstein' ? conditionColor: Color(0xff819ffe),
          lT: selectedCountry == 'Lithuania' ? conditionColor: Color(0xff819ffe),
          lU: selectedCountry == 'Luxembourg' ? conditionColor: Color(0xff819ffe),
          mO: selectedCountry == 'Macao' ? conditionColor: Color(0xff819ffe),
          mG: selectedCountry == 'Madagascar' ? conditionColor: Color(0xff819ffe),
          mW: selectedCountry == 'Malawi' ? conditionColor: Color(0xff819ffe),
          mY: selectedCountry == 'Malaysia' ? conditionColor: Color(0xff819ffe),
          mV: selectedCountry == 'Maldives' ? conditionColor: Color(0xff819ffe),
          mL: selectedCountry == 'Mali' ? conditionColor: Color(0xff819ffe),
          mT: selectedCountry == 'Malta' ? conditionColor: Color(0xff819ffe),
          mH: selectedCountry == 'Marshall Islands (the)' ? conditionColor: Color(0xff819ffe),
          mQ: selectedCountry == 'Martinique' ? conditionColor: Color(0xff819ffe),
          mR: selectedCountry == 'Mauritania' ? conditionColor: Color(0xff819ffe),
          mU: selectedCountry == 'Mauritius' ? conditionColor: Color(0xff819ffe),
          yT: selectedCountry == 'Mayotte' ? conditionColor: Color(0xff819ffe),
          mX: selectedCountry == 'Mexico' ? conditionColor: Color(0xff819ffe),
          fM: selectedCountry == 'Micronesia (Federated States of)' ? conditionColor: Color(0xff819ffe),
          mD: selectedCountry == 'Moldova (the Republic of)' ? conditionColor: Color(0xff819ffe),
          mC: selectedCountry == 'Monaco' ? conditionColor: Color(0xff819ffe),
          mN: selectedCountry == 'Mongolia' ? conditionColor: Color(0xff819ffe),
          mE: selectedCountry == 'Montenegro' ? conditionColor: Color(0xff819ffe),
          mS: selectedCountry == 'Montserrat' ? conditionColor: Color(0xff819ffe),
          mA: selectedCountry == 'Morocco' ? conditionColor: Color(0xff819ffe),
          mZ: selectedCountry == 'Mozambique' ? conditionColor: Color(0xff819ffe),
          mM: selectedCountry == 'Myanmar' ? conditionColor: Color(0xff819ffe),
          nA: selectedCountry == 'Namibia' ? conditionColor: Color(0xff819ffe),
          nR: selectedCountry == 'Nauru' ? conditionColor: Color(0xff819ffe),
          nP: selectedCountry == 'Nepal' ? conditionColor: Color(0xff819ffe),
          nL: selectedCountry == 'Netherlands (the)' ? conditionColor: Color(0xff819ffe),
          nC: selectedCountry == 'New Caledonia' ? conditionColor: Color(0xff819ffe),
          nZ: selectedCountry == 'New Zealand' ? conditionColor: Color(0xff819ffe),
          nI: selectedCountry == 'Nicaragua' ? conditionColor: Color(0xff819ffe),
          nE: selectedCountry == 'Niger (the)' ? conditionColor: Color(0xff819ffe),
          nG: selectedCountry == 'Nigeria' ? conditionColor: Color(0xff819ffe),
          nU: selectedCountry == 'Niue' ? conditionColor: Color(0xff819ffe),
          nF: selectedCountry == 'Norfolk Island' ? conditionColor: Color(0xff819ffe),
          mP: selectedCountry == 'Northern Mariana Islands (the)' ? conditionColor: Color(0xff819ffe),
          nO: selectedCountry == 'Norway' ? conditionColor: Color(0xff819ffe),
          oM: selectedCountry == 'Oman' ? conditionColor: Color(0xff819ffe),
          pK: selectedCountry == 'Pakistan' ? conditionColor: Color(0xff819ffe),
          pW: selectedCountry == 'Palau' ? conditionColor: Color(0xff819ffe),
          pS: selectedCountry == 'Palestine, State of' ? conditionColor: Color(0xff819ffe),
          pA: selectedCountry == 'Panama' ? conditionColor: Color(0xff819ffe),
          pG: selectedCountry == 'Papua New Guinea' ? conditionColor: Color(0xff819ffe),
          pY: selectedCountry == 'Paraguay' ? conditionColor: Color(0xff819ffe),
          pE: selectedCountry == 'Peru' ? conditionColor: Color(0xff819ffe),
          pH: selectedCountry == 'Philippines (the)' ? conditionColor: Color(0xff819ffe),
          pN: selectedCountry == 'Pitcairn' ? conditionColor: Color(0xff819ffe),
          pL: selectedCountry == 'Poland' ? conditionColor: Color(0xff819ffe),
          pT: selectedCountry == 'Portugal' ? conditionColor: Color(0xff819ffe),
          pR: selectedCountry == 'Puerto Rico' ? conditionColor: Color(0xff819ffe),
          qA: selectedCountry == 'Qatar' ? conditionColor: Color(0xff819ffe),
          rE: selectedCountry == 'Réunion' ? conditionColor: Color(0xff819ffe),
          rO: selectedCountry == 'Romania' ? conditionColor: Color(0xff819ffe),
          rU: selectedCountry == 'Russian Federation (the)' ? conditionColor: Color(0xff819ffe),
          rW: selectedCountry == 'Rwanda' ? conditionColor: Color(0xff819ffe),
          bL: selectedCountry == 'Saint Barthélemy' ? conditionColor: Color(0xff819ffe),
          sH: selectedCountry == 'Saint Helena, Ascension and Tristan da Cunha' ? conditionColor: Color(0xff819ffe),
          kN: selectedCountry == 'Saint Kitts and Nevis' ? conditionColor: Color(0xff819ffe),
          lC: selectedCountry == 'Saint Lucia' ? conditionColor: Color(0xff819ffe),
          mF: selectedCountry == 'Saint Martin (French part)' ? conditionColor: Color(0xff819ffe),
          pM: selectedCountry == 'Saint Pierre and Miquelon' ? conditionColor: Color(0xff819ffe),
          vC: selectedCountry == 'Saint Vincent and the Grenadines' ? conditionColor: Color(0xff819ffe),
          wS: selectedCountry == 'Samoa' ? conditionColor: Color(0xff819ffe),
          sM: selectedCountry == 'San Marino' ? conditionColor: Color(0xff819ffe),
          sT: selectedCountry == 'Sao Tome and Principe' ? conditionColor: Color(0xff819ffe),
          sA: selectedCountry == 'Saudi Arabia' ? conditionColor: Color(0xff819ffe),
          sN: selectedCountry == 'Senegal' ? conditionColor: Color(0xff819ffe),
          rS: selectedCountry == 'Serbia' ? conditionColor: Color(0xff819ffe),
          sC: selectedCountry == 'Seychelles' ? conditionColor: Color(0xff819ffe),
          sL: selectedCountry == 'Sierra Leone' ? conditionColor: Color(0xff819ffe),
          sG: selectedCountry == 'Singapore' ? conditionColor: Color(0xff819ffe),
          sX: selectedCountry == 'Sint Maarten (Dutch part)' ? conditionColor: Color(0xff819ffe),
          sK: selectedCountry == 'Slovakia' ? conditionColor: Color(0xff819ffe),
          sI: selectedCountry == 'Slovenia' ? conditionColor: Color(0xff819ffe),
          sB: selectedCountry == 'Solomon Islands' ? conditionColor: Color(0xff819ffe),
          sO: selectedCountry == 'Somalia' ? conditionColor: Color(0xff819ffe),
          zA: selectedCountry == 'South Africa' ? conditionColor: Color(0xff819ffe),
          gS: selectedCountry == 'South Georgia and the South Sandwich Islands' ? conditionColor: Color(0xff819ffe),
          sS: selectedCountry == 'South Sudan' ? conditionColor: Color(0xff819ffe),
          eS: selectedCountry == 'Spain' ? conditionColor: Color(0xff819ffe),
          lK: selectedCountry == 'Sri Lanka' ? conditionColor: Color(0xff819ffe),
          sD: selectedCountry == 'Sudan (the)' ? conditionColor: Color(0xff819ffe),
          sR: selectedCountry == 'Suriname' ? conditionColor: Color(0xff819ffe),
          sJ: selectedCountry == 'Svalbard and Jan Mayen' ? conditionColor: Color(0xff819ffe),
          sE: selectedCountry == 'Sweden' ? conditionColor: Color(0xff819ffe),
          cH: selectedCountry == 'Switzerland' ? conditionColor: Color(0xff819ffe),
          sY: selectedCountry == 'Syrian Arab Republic (the)' ? conditionColor: Color(0xff819ffe),
          tW: selectedCountry == 'Taiwan (Province of China)' ? conditionColor: Color(0xff819ffe),
          tJ: selectedCountry == 'Tajikistan' ? conditionColor: Color(0xff819ffe),
          tZ: selectedCountry == 'Tanzania, United Republic of' ? conditionColor: Color(0xff819ffe),
          tH: selectedCountry == 'Thailand' ? conditionColor: Color(0xff819ffe),
          tL: selectedCountry == 'Timor-Leste' ? conditionColor: Color(0xff819ffe),
          tG: selectedCountry == 'Togo' ? conditionColor: Color(0xff819ffe),
          tK: selectedCountry == 'Tokelau' ? conditionColor: Color(0xff819ffe),
          tO: selectedCountry == 'Tonga' ? conditionColor: Color(0xff819ffe),
          tT: selectedCountry == 'Trinidad and Tobago' ? conditionColor: Color(0xff819ffe),
          tN: selectedCountry == 'Tunisia' ? conditionColor: Color(0xff819ffe),
          tR: selectedCountry == 'Turkey' ? conditionColor: Color(0xff819ffe),
          tM: selectedCountry == 'Turkmenistan' ? conditionColor: Color(0xff819ffe),
          tC: selectedCountry == 'Turks and Caicos Islands (the)' ? conditionColor: Color(0xff819ffe),
          tV: selectedCountry == 'Tuvalu' ? conditionColor: Color(0xff819ffe),
          uG: selectedCountry == 'Uganda' ? conditionColor: Color(0xff819ffe),
          uA: selectedCountry == 'Ukraine' ? conditionColor: Color(0xff819ffe),
          aE: selectedCountry == 'United Arab Emirates (the)' ? conditionColor: Color(0xff819ffe),
          gB: selectedCountry == 'United Kingdom of Great Britain and Northern Ireland (the)' ? conditionColor: Color(0xff819ffe),
          uS: selectedCountry == 'United States' ? conditionColor: Color(0xff819ffe),
          uY: selectedCountry == 'Uruguay' ? conditionColor: Color(0xff819ffe),
          uZ: selectedCountry == 'Uzbekistan' ? conditionColor: Color(0xff819ffe),
          vU: selectedCountry == 'Vanuatu' ? conditionColor: Color(0xff819ffe),
          vE: selectedCountry == 'Venezuela (Bolivarian Republic of)' ? conditionColor: Color(0xff819ffe),
          vN: selectedCountry == 'Viet Nam' ? conditionColor: Color(0xff819ffe),
          wF: selectedCountry == 'Wallis and Futuna' ? conditionColor: Color(0xff819ffe),
          eH: selectedCountry == 'Western Sahara' ? conditionColor: Color(0xff819ffe),
          yE: selectedCountry == 'Yemen' ? conditionColor: Color(0xff819ffe),
          zM: selectedCountry == 'Zambia' ? conditionColor: Color(0xff819ffe),
          zW: selectedCountry == 'Zimbabwe' ? conditionColor: Color(0xff819ffe),
        ).toMap(),
      
      // Details of what area is being touched, giving you the ID, name and tapdetails
      callback: (id, name, tapdetails) {      
          print(id); 
      },
      ),
    );
  }
}
